#+BLOG: Unixbhaskar's Blog
#+POSTID: 1243
#+title: How To Tap Potentials Of FFMPEG
#+date: 2023-03-23
#+tags: Technical Bash Scripting

Well, when I started to use a tool(in this case ffmpeg), like everyone else in
the wild started to poke and find out stuff that adds benefit to the work I do.

Here in this post, I will focus only on *Two* aspects or utilities of FFMPEG which
enhance my fiddling with it.

The first, one is, called /*Drawtext*/. Which basically allows you to draw text on
ffmpeg created video. As a result, you can put explanatory text on the video to
make the audience to aware of specific facts about the video.

Let me give you an example,I made a video about it a few months back, which
can be seen here at [[https://youtu.be/-rpRa9caSvU][Youtube_Video_Showing_Drawing_Text_On_Recorded_Video]] .


Alright, the next is *how to cut specific sections of a video or audio* from an
existing audio/video. It helps to filter out the stuff you are specifically
interested in.

Again, I am using asciinema to record the actions , take a peek :

Here is the [[https://asciinema.org/a/569411][Asciinema Recording of ffmpeg cut]] .


Now, you saw that I have used a script name /ffmpeg_cut/ , which is just a few
lines of script to get the job done in a semi-autometic way.

Here is the script for your perusal :

#+BEGIN_SRC bash
#!/usr/bin/env bash

# Provide time in seconds

start_time=$1
source_file=$2
end_time=$3
modifed_file=$4


if [[ $# -lt 4 ]];then

	echo You are suppose to provide four parameter to this script
	echo Times should be given in seconds
	echo $(basename $0) start_time source_file end_time modifed_file
	exit 1
fi

$(command -v ffmpeg) -ss ${start_time} -i ${source_file} -t ${end_time} -c copy ${modifed_file}.mp3

#+END_SRC

I believe nothing more to explain, this is certainly a /newbie/ kind of script to
perform a specific task. Although, it could have been made more complex by
adding your specific requirement. At this moment, it is alright, in the future, if
I need some enhancement to it, will do it then.
