#+BLOG: Unixbhaskar's Blog
#+POSTID: 1907
#+title: Linux Error Codes Explained
#+date: 2024-09-28
#+tags: Technical Tools Opensource Symbols Debug Errorcode

Alright, while sitting on Linux makes you happy and productive. But,the time
will come when you are thrown into the dark state of via some /arcane and
esoteric/ mnemonics and numbers thrown at you as an error signature.

Meh,what an unpleasant surprise! Provided you are not accustomed with some well
defined *error code* to find out the underlying cause. And if you know, you time
to mitigate the problem get reduced a great deal.Importantly, it saves you from
fanatically searching the internet for something very unknown to most people.

So, here I will merely guide you to get hold of the damn thing by the easiest
possible way to discover and narrowed down the search and fix time.

How do you do that? People are curious and some wise soul has already done the
hard part for you(this is a clear boon of using open source) that somebody
encountered the problem you are facing right now and hopefully have the solution
and share it publicly.

* Get /moreutils/ package from your OS package repository

And in that package there is a binary called, /errno/ , that will help you to
figure out all the mnemonics of the error throwing at you.

Here is an example to *list all the error mnemonics and numbers* ...

Just type *errno -l* at the terminal and it show something like this :

#+BEGIN_SRC bash
bhaskar_08:41:19_Sat Sep 28: :~>errno -l
EPERM 1 Operation not permitted
ENOENT 2 No such file or directory
ESRCH 3 No such process
EINTR 4 Interrupted system call
EIO 5 Input/output error
ENXIO 6 No such device or address
E2BIG 7 Argument list too long
ENOEXEC 8 Exec format error
EBADF 9 Bad file descriptor
ECHILD 10 No child processes
EAGAIN 11 Resource temporarily unavailable
ENOMEM 12 Cannot allocate memory
EACCES 13 Permission denied
EFAULT 14 Bad address
ENOTBLK 15 Block device required
EBUSY 16 Device or resource busy
EEXIST 17 File exists
EXDEV 18 Invalid cross-device link
ENODEV 19 No such device
ENOTDIR 20 Not a directory
EISDIR 21 Is a directory
EINVAL 22 Invalid argument
ENFILE 23 Too many open files in system
EMFILE 24 Too many open files
ENOTTY 25 Inappropriate ioctl for device
ELIBBAD 80 Accessing a corrupted shared library
ELIBSCN 81 .lib section in a.out corrupted
ELIBMAX 82 Attempting to link in too many shared libraries
ELIBEXEC 83 Cannot exec a shared library directly
EILSEQ 84 Invalid or incomplete multibyte or wide character
ERESTART 85 Interrupted system call should be restarted
ESTRPIPE 86 Streams pipe error
EUSERS 87 Too many users
ENOTSOCK 88 Socket operation on non-socket
EDESTADDRREQ 89 Destination address required
EMSGSIZE 90 Message too long
EPROTOTYPE 91 Protocol wrong type for socket
ENOPROTOOPT 92 Protocol not available
EPROTONOSUPPORT 93 Protocol not supported
ESOCKTNOSUPPORT 94 Socket type not supported
EOPNOTSUPP 95 Operation not supported
EPFNOSUPPORT 96 Protocol family not supported
EAFNOSUPPORT 97 Address family not supported by protocol
EADDRINUSE 98 Address already in use
EADDRNOTAVAIL 99 Cannot assign requested address
ENETDOWN 100 Network is down
ENETUNREACH 101 Network is unreachable
ENETRESET 102 Network dropped connection on reset
ECONNABORTED 103 Software caused connection abort
ECONNRESET 104 Connection reset by peer
ENOBUFS 105 No buffer space available
EISCONN 106 Transport endpoint is already connected
ENOTCONN 107 Transport endpoint is not connected
ESHUTDOWN 108 Cannot send after transport endpoint shutdown
ETOOMANYREFS 109 Too many references: cannot splice
ETIMEDOUT 110 Connection timed out
ECONNREFUSED 111 Connection refused
EHOSTDOWN 112 Host is down
EHOSTUNREACH 113 No route to host
EALREADY 114 Operation already in progress
EINPROGRESS 115 Operation now in progress
ESTALE 116 Stale file handle
EUCLEAN 117 Structure needs cleaning
ENOTNAM 118 Not a XENIX named type file
ENAVAIL 119 No XENIX semaphores available
EISNAM 120 Is a named type file
EREMOTEIO 121 Remote I/O error
EDQUOT 122 Disk quota exceeded
ENOMEDIUM 123 No medium found
EMEDIUMTYPE 124 Wrong medium type
ECANCELED 125 Operation canceled
ENOKEY 126 Required key not available
EKEYEXPIRED 127 Key has expired
EKEYREVOKED 128 Key has been revoked
EKEYREJECTED 129 Key was rejected by service
EOWNERDEAD 130 Owner died
ENOTRECOVERABLE 131 State not recoverable
ERFKILL 132 Operation not possible due to RF-kill
EHWPOISON 133 Memory page has hardware error
ENOTSUP 95 Operation not supported
#+END_SRC

See! How abject easy to get it right on your machine without going out to the
internet and spending hours after hours doing blatant searches with wild
assumptions.

In my current system it shows precisely 134 entry of it :

#+BEGIN_SRC bash
bhaskar_08:44:36_Sat Sep 28: :~>errno -l | wc -l
134
#+END_SRC

Okay, if you like to see the demo of me doing the stuff live, you might take a
peek of my  [[https://youtu.be/2swhluLFt_o?si=7pgk7xmjmxCTENOx][YouTube Video]] .
